# Generated by Django 6.1.1 on 2026-09-25 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_groundstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('ground_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.groundstation')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.satellite')),
            ],
        ),
    ]
